accountFill = '''insert into users (email, fullname, faculty_id, password) values ('Деев Александр Владимирович', 'Деев Александр Владимирович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Купцов Кирилл Александрович', 'Купцов Кирилл Александрович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Матецкая Марина Владимировна', 'Матецкая Марина Владимировна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Шепелева Софья Александровна', 'Шепелева Софья Александровна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Васильева Екатерина Дмитриевна', 'Васильева Екатерина Дмитриевна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Корчак Анна Эдуардовна', 'Корчак Анна Эдуардовна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Шапошникова Ксения Олеговна', 'Шапошникова Ксения Олеговна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Петрухин Владимир Яковлевич', 'Петрухин Владимир Яковлевич', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Сорвин Кирилл Валентинович', 'Сорвин Кирилл Валентинович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Текутьев Дмитрий Иванович', 'Текутьев Дмитрий Иванович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Пучков Павел Андреевич', 'Пучков Павел Андреевич', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Селиванова Ирина Владимировна', 'Селиванова Ирина Владимировна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Уланов Владимир Леонидович', 'Уланов Владимир Леонидович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Хомченкова Варвара Валентиновна', 'Хомченкова Варвара Валентиновна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Филатов Николай Александрович', 'Филатов Николай Александрович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Захарова Аглая Валентиновна', 'Захарова Аглая Валентиновна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Гусева Наталия Михайловна', 'Гусева Наталия Михайловна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Борзенко Виктор Витальевич', 'Борзенко Виктор Витальевич', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Павлов Сергей Владимирович', 'Павлов Сергей Владимирович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Танис Кристина Александровна', 'Танис Кристина Александровна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Янчева Анастасия Вадимовна', 'Янчева Анастасия Вадимовна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Казун Антон Павлович', 'Казун Антон Павлович', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Гоголева Ирина Викторовна', 'Гоголева Ирина Викторовна', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Обухов Алексей Сергеевич', 'Обухов Алексей Сергеевич', 4, 'e3vdbEAt');
insert into users (email, fullname, faculty_id, password) values ('Измагурова Виктория Леонидовна', 'Измагурова Виктория Леонидовна', 4, 'e3vdbEAt');
'''