categoryFill = '''insert into categories (category, is_custom) values ('компьютерная грамотность', false);
insert into categories (category, is_custom) values ('волонтерский центр', false);
insert into categories (category, is_custom) values ('волонтерство', false);
insert into categories (category, is_custom) values ('подготовка мероприятий', false);
insert into categories (category, is_custom) values ('продвижение', false);
insert into categories (category, is_custom) values ('проектная деятельность', false);
insert into categories (category, is_custom) values ('event management', false);
insert into categories (category, is_custom) values ('выпускники', false);
insert into categories (category, is_custom) values ('конкурс', false);
insert into categories (category, is_custom) values ('образование', false);
insert into categories (category, is_custom) values ('олимпиады', false);
insert into categories (category, is_custom) values ('организация массовых мероприятий', false);
insert into categories (category, is_custom) values ('студенты', false);
insert into categories (category, is_custom) values ('школьники', false);
insert into categories (category, is_custom) values ('межкультурная коммуникация', false);
insert into categories (category, is_custom) values ('перевод', false);
insert into categories (category, is_custom) values ('психология', false);
insert into categories (category, is_custom) values ('социальная психология', false);
insert into categories (category, is_custom) values ('аналитические способности', false);
insert into categories (category, is_custom) values ('поиск информации', false);
insert into categories (category, is_custom) values ('система образования', false);
insert into categories (category, is_custom) values ('приемная кампания', false);
insert into categories (category, is_custom) values ('социологические исследования', false);
insert into categories (category, is_custom) values ('3D проектирование', false);
insert into categories (category, is_custom) values ('campus life', false);
insert into categories (category, is_custom) values ('history', false);
insert into categories (category, is_custom) values ('student life', false);
insert into categories (category, is_custom) values ('education and labor market outcomes', false);
insert into categories (category, is_custom) values ('law', false);
insert into categories (category, is_custom) values ('абитуриенты', false);
insert into categories (category, is_custom) values ('медиадискурс', false);
insert into categories (category, is_custom) values ('общество', false);
insert into categories (category, is_custom) values ('СМИ', false);
insert into categories (category, is_custom) values ('языки', false);
insert into categories (category, is_custom) values ('зарубежный опыт', false);
insert into categories (category, is_custom) values ('мировая энергетика', false);
insert into categories (category, is_custom) values ('научная работа', false);
insert into categories (category, is_custom) values ('открытые данные', false);
insert into categories (category, is_custom) values ('развитие', false);
insert into categories (category, is_custom) values ('факторы успешности инноваций', false);
insert into categories (category, is_custom) values ('дискуссионный клуб', false);
insert into categories (category, is_custom) values ('книги', false);
insert into categories (category, is_custom) values ('художественный перевод', false);
insert into categories (category, is_custom) values ('онлайн-образование', false);
insert into categories (category, is_custom) values ('древнегреческий язык', false);
insert into categories (category, is_custom) values ('латынь', false);
insert into categories (category, is_custom) values ('роман', false);
insert into categories (category, is_custom) values ('филология', false);
insert into categories (category, is_custom) values ('контрольно-надзорная деятельность', false);
insert into categories (category, is_custom) values ('противодействие коррупции', false);
insert into categories (category, is_custom) values ('цифровые технологии', false);
insert into categories (category, is_custom) values ('медиацентр', false);
insert into categories (category, is_custom) values ('digital humanities', false);
insert into categories (category, is_custom) values ('база данных', false);
insert into categories (category, is_custom) values ('кинематограф', false);
insert into categories (category, is_custom) values ('SMM', false);
insert into categories (category, is_custom) values ('аудиоподкастинг', false);
insert into categories (category, is_custom) values ('медиа', false);
insert into categories (category, is_custom) values ('пиар', false);
insert into categories (category, is_custom) values ('работа с аудиозаписями', false);
insert into categories (category, is_custom) values ('обзор литературы', false);
insert into categories (category, is_custom) values ('социология', false);
insert into categories (category, is_custom) values ('эмпирическое исследование', false);
insert into categories (category, is_custom) values ('визуальный контент', false);
insert into categories (category, is_custom) values ('составление карты', false);
insert into categories (category, is_custom) values ('работа в команде', false);
insert into categories (category, is_custom) values ('самоорганизация', false);
insert into categories (category, is_custom) values ('стажировка', false);
insert into categories (category, is_custom) values ('умение работать в команде', false);
insert into categories (category, is_custom) values ('веб-программирование', false);
insert into categories (category, is_custom) values ('веб-разработка', false);
insert into categories (category, is_custom) values ('компьютерная графика', false);
insert into categories (category, is_custom) values ('исследование образования', false);
insert into categories (category, is_custom) values ('экспедиция', false);
insert into categories (category, is_custom) values ('анализ данных', false);
insert into categories (category, is_custom) values ('практика', false);
insert into categories (category, is_custom) values ('проведение интервью', false);
insert into categories (category, is_custom) values ('этнография', false);
insert into categories (category, is_custom) values ('иностранные студенты', false);
'''