categoryFill = '''
insert into categories (category, is_custom) values ('3D проектирование', false);
insert into categories (category, is_custom) values ('big datacampus life', false);
insert into categories (category, is_custom) values ('education and labor market outcomes', false);
insert into categories (category, is_custom) values ('event management', false);
insert into categories (category, is_custom) values ('history', false);
insert into categories (category, is_custom) values ('IT-технологии', false);
insert into categories (category, is_custom) values ('law', false);
insert into categories (category, is_custom) values ('LegalTech', false);
insert into categories (category, is_custom) values ('practicelaw', false);
insert into categories (category, is_custom) values ('SMM', false);
insert into categories (category, is_custom) values ('student life', false);
insert into categories (category, is_custom) values ('абитуриенты', false);
insert into categories (category, is_custom) values ('автоматизация управления', false);
insert into categories (category, is_custom) values ('Азия', false);
insert into categories (category, is_custom) values ('активное долголетие', false);
insert into categories (category, is_custom) values ('анализ данных', false);
insert into categories (category, is_custom) values ('анализ финансовой отчетности', false);
insert into categories (category, is_custom) values ('антикоррупция', false);
insert into categories (category, is_custom) values ('Апрельская конференция', false);
insert into categories (category, is_custom) values ('арабский язык', false);
insert into categories (category, is_custom) values ('Армения', false);
insert into categories (category, is_custom) values ('ассистент', false);
insert into categories (category, is_custom) values ('аудиоподкастинг', false);
insert into categories (category, is_custom) values ('аудит', false);
insert into categories (category, is_custom) values ('бизнес-процесс', false);
insert into categories (category, is_custom) values ('большие данные', false);
insert into categories (category, is_custom) values ('бренд ВШЭ', false);
insert into categories (category, is_custom) values ('бюджетные расходы', false);
insert into categories (category, is_custom) values ('вакансия', false);
insert into categories (category, is_custom) values ('веб-дизайн', false);
insert into categories (category, is_custom) values ('видео', false);
insert into categories (category, is_custom) values ('видеоблоги', false);
insert into categories (category, is_custom) values ('видеоматериалы', false);
insert into categories (category, is_custom) values ('видеомонтаж', false);
insert into categories (category, is_custom) values ('видеопроизводство', false);
insert into categories (category, is_custom) values ('видеосъемка', false);
insert into categories (category, is_custom) values ('визуализация данных', false);
insert into categories (category, is_custom) values ('внешняя политика', false);
insert into categories (category, is_custom) values ('востоковедение', false);
insert into categories (category, is_custom) values ('выпускники', false);
insert into categories (category, is_custom) values ('высшее образование', false);
insert into categories (category, is_custom) values ('городское развитие', false);
insert into categories (category, is_custom) values ('госзакупки', false);
insert into categories (category, is_custom) values ('государственное ценообразование', false);
insert into categories (category, is_custom) values ('дизайн', false);
insert into categories (category, is_custom) values ('дизайн макета', false);
insert into categories (category, is_custom) values ('дизайн материалов', false);
insert into categories (category, is_custom) values ('добрососедство', false);
insert into categories (category, is_custom) values ('древнегреческий язык', false);
insert into categories (category, is_custom) values ('журналистика', false);
insert into categories (category, is_custom) values ('законодательство', false);
insert into categories (category, is_custom) values ('закупки', false);
insert into categories (category, is_custom) values ('зарубежный опыт', false);
insert into categories (category, is_custom) values ('защита заявителя', false);
insert into categories (category, is_custom) values ('изучение контрагентов', false);
insert into categories (category, is_custom) values ('Индия', false);
insert into categories (category, is_custom) values ('инновационная продукция', false);
insert into categories (category, is_custom) values ('иностранные студенты', false);
insert into categories (category, is_custom) values ('интеграция', false);
insert into categories (category, is_custom) values ('интерактивные методы обучения', false);
insert into categories (category, is_custom) values ('интервью', false);
insert into categories (category, is_custom) values ('информационная поддержка', false);
insert into categories (category, is_custom) values ('исследовательская работа', false);
insert into categories (category, is_custom) values ('историческая память', false);
insert into categories (category, is_custom) values ('история', false);
insert into categories (category, is_custom) values ('Казахстан', false);
insert into categories (category, is_custom) values ('Калининградская область', false);
insert into categories (category, is_custom) values ('каталоги', false);
insert into categories (category, is_custom) values ('качественное исследование', false);
insert into categories (category, is_custom) values ('кинематограф', false);
insert into categories (category, is_custom) values ('киноиндустрия', false);
insert into categories (category, is_custom) values ('кинопроизводство', false);
insert into categories (category, is_custom) values ('киносценарий', false);
insert into categories (category, is_custom) values ('Китай', false);
insert into categories (category, is_custom) values ('компьютерная грамотность', false);
insert into categories (category, is_custom) values ('конкурс', false);
insert into categories (category, is_custom) values ('Конструктор договоров', false);
insert into categories (category, is_custom) values ('контент-менеджмент', false);
insert into categories (category, is_custom) values ('контрольно-надзорная деятельность', false);
insert into categories (category, is_custom) values ('конференция', false);
insert into categories (category, is_custom) values ('копирайтинг', false);
insert into categories (category, is_custom) values ('коррупция', false);
insert into categories (category, is_custom) values ('культурология', false);
insert into categories (category, is_custom) values ('латынь', false);
insert into categories (category, is_custom) values ('лингвистика', false);
insert into categories (category, is_custom) values ('маркетинг', false);
insert into categories (category, is_custom) values ('мегаполисы', false);
insert into categories (category, is_custom) values ('медиа', false);
insert into categories (category, is_custom) values ('медиаграмотность', false);
insert into categories (category, is_custom) values ('медиаплан', false);
insert into categories (category, is_custom) values ('медиапродукт', false);
insert into categories (category, is_custom) values ('международные отношения', false);
insert into categories (category, is_custom) values ('методы социологического исследования', false);
insert into categories (category, is_custom) values ('мировая экономика', false);
insert into categories (category, is_custom) values ('мировая энергетика', false);
insert into categories (category, is_custom) values ('молодежная конференция', false);
insert into categories (category, is_custom) values ('Москва', false);
insert into categories (category, is_custom) values ('написание текстов', false);
insert into categories (category, is_custom) values ('нарратив', false);
insert into categories (category, is_custom) values ('научная конференция', false);
insert into categories (category, is_custom) values ('научная работа', false);
insert into categories (category, is_custom) values ('научно-исследовательская работа', false);
insert into categories (category, is_custom) values ('неравенство', false);
insert into categories (category, is_custom) values ('НКО', false);
insert into categories (category, is_custom) values ('нормативные правовые акты', false);
insert into categories (category, is_custom) values ('образование', false);
insert into categories (category, is_custom) values ('образовательные услуги', false);
insert into categories (category, is_custom) values ('общественная активность', false);
insert into categories (category, is_custom) values ('олимпиады', false);
insert into categories (category, is_custom) values ('онлайн курсы', false);
insert into categories (category, is_custom) values ('онлайн-образование', false);
insert into categories (category, is_custom) values ('организация конференции', false);
insert into categories (category, is_custom) values ('организация массовых мероприятий', false);
insert into categories (category, is_custom) values ('организация мероприятия', false);
insert into categories (category, is_custom) values ('открытые данные', false);
insert into categories (category, is_custom) values ('перевод', false);
insert into categories (category, is_custom) values ('пиар', false);
insert into categories (category, is_custom) values ('поиск информации', false);
insert into categories (category, is_custom) values ('политология', false);
insert into categories (category, is_custom) values ('потребительский рынок', false);
insert into categories (category, is_custom) values ('право', false);
insert into categories (category, is_custom) values ('правовая аналитика', false);
insert into categories (category, is_custom) values ('правовое регулирование', false);
insert into categories (category, is_custom) values ('практика', false);
insert into categories (category, is_custom) values ('практическая юриспруденция', false);
insert into categories (category, is_custom) values ('прикладные исследования', false);
insert into categories (category, is_custom) values ('проведение интервью', false);
insert into categories (category, is_custom) values ('прогнозирование', false);
insert into categories (category, is_custom) values ('программирование', false);
insert into categories (category, is_custom) values ('программирование в R/Python', false);
insert into categories (category, is_custom) values ('продвижение в Интернете', false);
insert into categories (category, is_custom) values ('продюсирование', false);
insert into categories (category, is_custom) values ('проектная деятельность', false);
insert into categories (category, is_custom) values ('противодействие коррупции', false);
insert into categories (category, is_custom) values ('профессиональные и карьерные предпочтения студентов', false);
insert into categories (category, is_custom) values ('психология', false);
insert into categories (category, is_custom) values ('ПУЛАП', false);
insert into categories (category, is_custom) values ('работа с литературой', false);
insert into categories (category, is_custom) values ('развитие', false);
insert into categories (category, is_custom) values ('развитие регионов', false);
insert into categories (category, is_custom) values ('развитие университетов', false);
insert into categories (category, is_custom) values ('разработка сайтов', false);
insert into categories (category, is_custom) values ('разработка сценария', false);
insert into categories (category, is_custom) values ('расшифровка интервью', false);
insert into categories (category, is_custom) values ('региональное управление', false);
insert into categories (category, is_custom) values ('регионы России', false);
insert into categories (category, is_custom) values ('редактирование', false);
insert into categories (category, is_custom) values ('редакция', false);
insert into categories (category, is_custom) values ('роман', false);
insert into categories (category, is_custom) values ('рынок труда', false);
insert into categories (category, is_custom) values ('санкции', false);
insert into categories (category, is_custom) values ('социальная антропология', false);
insert into categories (category, is_custom) values ('социально-экономическое развитие', false);
insert into categories (category, is_custom) values ('социальные сети', false);
insert into categories (category, is_custom) values ('социолингвистика', false);
insert into categories (category, is_custom) values ('социология', false);
insert into categories (category, is_custom) values ('социология образования', false);
insert into categories (category, is_custom) values ('сравнительно-правовой анализ', false);
insert into categories (category, is_custom) values ('стартапы', false);
insert into categories (category, is_custom) values ('стратегии бизнеса', false);
insert into categories (category, is_custom) values ('студенты', false);
insert into categories (category, is_custom) values ('суд', false);
insert into categories (category, is_custom) values ('судебная практика', false);
insert into categories (category, is_custom) values ('сценарий', false);
insert into categories (category, is_custom) values ('технологические платформы', false);
insert into categories (category, is_custom) values ('ток-шоу', false);
insert into categories (category, is_custom) values ('туризм', false);
insert into categories (category, is_custom) values ('умение работать в команде', false);
insert into categories (category, is_custom) values ('устойчивое развитие', false);
insert into categories (category, is_custom) values ('учебно-методические материалы', false);
insert into categories (category, is_custom) values ('факторы успешности инноваций', false);
insert into categories (category, is_custom) values ('филология', false);
insert into categories (category, is_custom) values ('финансовая отчетность', false);
insert into categories (category, is_custom) values ('финансовая сфера', false);
insert into categories (category, is_custom) values ('финансовое право', false);
insert into categories (category, is_custom) values ('финансы', false);
insert into categories (category, is_custom) values ('фото- и видеосъемка мероприятий', false);
insert into categories (category, is_custom) values ('цифровая экономика', false);
insert into categories (category, is_custom) values ('цифровые технологии', false);
insert into categories (category, is_custom) values ('школьники', false);
insert into categories (category, is_custom) values ('экономика', false);
insert into categories (category, is_custom) values ('экономика города', false);
insert into categories (category, is_custom) values ('экономический анализ', false);
insert into categories (category, is_custom) values ('экспедиция', false);
insert into categories (category, is_custom) values ('экспертиза нпа', false);
insert into categories (category, is_custom) values ('экспертно-аналитическая деятельность', false);
insert into categories (category, is_custom) values ('эксперты', false);
insert into categories (category, is_custom) values ('электронная библиотека', false);
insert into categories (category, is_custom) values ('Юго-Восточная Азия', false);
insert into categories (category, is_custom) values ('юридическая техника', false);
insert into categories (category, is_custom) values ('юридическое письмо', false);
insert into categories (category, is_custom) values ('языки', false);
insert into categories (category, is_custom) values ('языковой клуб', false);
insert into categories (category, is_custom) values ('языковой корпус', false);
'''