accountSql = ''' DROP TABLE IF EXISTS users CASCADE;
 CREATE TABLE users (
 ID SERIAL PRIMARY KEY NOT NULL,
 EMAIL text NOT NULL UNIQUE,
 FULLNAME text NOT NULL,
 LAST_LOGIN DATE,
 DESCRIPTION TEXT,
 FACULTY_ID BIGINT REFERENCES FACULTIES,
 PASSWORD text NOT NULL,
 CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
 UPDATED_DATE DATE
 )
 ''';

accountFill = ''' INSERT INTO users (EMAIL, FULLNAME, FACULTY_ID, PASSWORD) 
 VALUES('test@test.ru', 'TEST', (SELECT id from faculties WHERE ID='1'), '1');'''