applicationSql = ''' DROP TABLE IF EXISTS applications CASCADE;
 CREATE TABLE applications (
 ID SERIAL NOT NULL,
 PROJECT_ID BIGINT REFERENCES PROJECTS,
 APPLICANT_ID BIGINT REFERENCES users,
 CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
 MESSAGE text NOT NULL,
 STATUS BIGINT REFERENCES statuses,
 PRIMARY KEY (ID, PROJECT_ID, APPLICANT_ID)
 )
 ''';

applicationFill = ''' INSERT INTO applications (PROJECT_ID, APPLICANT_ID, MESSAGE, STATUS)
 VALUES((SELECT id from projects WHERE ID='1'), (SELECT id from users WHERE id = '1'), 'Accept me',
 (SELECT id from statuses WHERE STATUS='SENT'))'''