projectSql = ''' DROP TABLE IF EXISTS projects CASCADE;
 CREATE TABLE projects (
 ID SERIAL PRIMARY KEY NOT NULL,
 NAME text NOT NULL,
 DESCRIPTION text NOT NULL,
 CONTACTS text,
 CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
 UPDATED_DATE DATE,
 START_DATE DATE,
 END_DATE DATE,
 CREATOR_USER_ID BIGINT REFERENCES users,
 IS_CLOSED BOOLEAN
 )
 ''';

projectFill = ''' INSERT INTO projects (NAME, DESCRIPTION, START_DATE, END_DATE, CREATOR_USER_ID, IS_CLOSED)
 VALUES('TEST', 'TESTDESC', '2022-01-30', '2023-02-14', (SELECT id from users WHERE EMAIL='test@test.ru'), 
 FALSE)'''